# MIT License
# Autor atual: David Assef
# Descrição: Compose de desenvolvimento do ReciboFast (backend + proxy opcional)
# Data: 29-08-2025

version: "3.9"
services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env.example
    ports:
      - "8080:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M

# Frontend e proxy reverso podem ser adicionados posteriormente.
