# Autor: David Assef
# Descrição: Pipeline CI para build, testes unitários (Vitest) e E2E (Playwright) do frontend
# Data: 12-09-2025
# MIT License

name: CI Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package.json

      - name: Install dependencies
        run: npm ci

      - name: Unit tests (Vitest)
        run: npm run test -- --run

      - name: Build
        env:
          VITE_HCAPTCHA_SITE_KEY: ${{ secrets.VITE_HCAPTCHA_SITE_KEY }}
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: E2E tests (Playwright via vite preview)
        env:
          CI: 'true'
          PLAYWRIGHT_BASE_URL: 'http://localhost:5173'
          VITE_HCAPTCHA_SITE_KEY: ${{ secrets.VITE_HCAPTCHA_SITE_KEY }}
          VITE_E2E_BYPASS: '1'
        run: npm run e2e

      - name: Prepare Vercel hook env
        env:
          VERCEL_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
        run: |
          if [ -n "${VERCEL_DEPLOY_HOOK_URL}" ]; then
            echo "HAS_VERCEL_HOOK=true" >> "$GITHUB_ENV"
            echo "VERCEL_DEPLOY_HOOK_URL=${VERCEL_DEPLOY_HOOK_URL}" >> "$GITHUB_ENV"
          else
            echo "HAS_VERCEL_HOOK=false" >> "$GITHUB_ENV"
          fi

      - name: Trigger Vercel Deploy (Production)
        if: ${{ env.HAS_VERCEL_HOOK == 'true' }}
        run: |
          echo "Triggering Vercel Deploy via Hook"
          curl -s -X POST "$VERCEL_DEPLOY_HOOK_URL" || true
